// Verbatim mirror of be_finanaces_vanapalli/src/lib/reservedUsernames.ts.
// Both backends gate the shared identity table, so the reserved list must
// stay in lockstep. Keep changes in sync by hand.
const RESERVED = new Set<string>([
  // Brand / staff
  "vanapalli",
  "admin",
  "administrator",
  "root",
  "owner",
  "support",
  "help",
  "info",
  "contact",
  "team",
  "staff",
  "moderator",
  "mod",
  "official",
  "system",
  "security",
  "abuse",
  "legal",
  "privacy",
  "terms",
  "billing",
  "noreply",
  "no_reply",
  // Generic
  "user",
  "users",
  "guest",
  "anonymous",
  "anon",
  "me",
  "you",
  "everyone",
  "all",
  "null",
  "undefined",
  "none",
  "nil",
  "default",
  "test",
  "demo",
  "example",
  // Service-y
  "api",
  "auth",
  "login",
  "signup",
  "signin",
  "logout",
  "oauth",
  "callback",
  "www",
  "mail",
  "email",
  "ftp",
  "ssh",
  "static",
  "assets",
  "cdn",
  "search",
  "settings",
  "profile",
  "profiles",
  "account",
  "accounts",
  "home",
  // Finance-specific
  "finances",
  "finance",
  "money",
  "wallet",
  "bills",
  "split",
  "splits",
  "group",
  "groups",
  "budget",
  "budgets",
  "expense",
  "expenses",
]);

export function isReservedUsername(usernameLower: string): boolean {
  return RESERVED.has(usernameLower);
}
